# Introduction to Python

This introduction to Python will focus on the second of two main topics: tools for data manipulation, analysis, and plotting.

We will cover:
- Pandas library and dataframes,
- computing statistics from data,
- finding relationships in data,
- plotting data to show relationships.

As a reminder:
IPython notebooks are organized by "cells." Each cell can have its own code and can be run independently and in any order (although they are usually run top to bottom in a notebook.) To run a cell and move to the next cell press ```Shift+Enter```. To run a cell and stay on that cell press ```Control+Enter```.

Questions to be discussed in groups are highlighted in <font color='green'>green</font>. If you don't understand a function that is used, try googling something like "python function-name".

In [4]:
import pandas as pd # Library for storing, manipulating, and visualizing data
import matplotlib.pyplot as plt # Library for plotting
%matplotlib inline

In [5]:
# We'll use the same data as before
file_name = 'student_data.csv'

# Dataframes
Rather than dealing with loading the csv data ourselves, we can use the Pandas library to directly read the csv and store is in a data structure called a "Dataframe." Dataframes are objects that can be used to store and manipulate 'columnar' data.

One nice features of dataframes is that they are a structure that can store both the raw data and also meta-data, e.g. student ID/name or assignment type.

In [6]:
# Read csv into dataframe
df = pd.read_csv(file_name)
df

     ID       MT1       MT2        HW     Final
0   100  0.618561  0.523077  0.712692  0.810502
1   101  0.566880  0.498883  0.657585  0.537925
2   102  0.567084  1.000000  0.758540  0.503278
3   103  1.000000  0.576961  0.592728  0.987362
4   104  0.703201  0.529477  0.706027  0.632194
5   105  0.858572  0.575547  0.657599  0.659696
6   106  0.265628  0.503418  0.735388  0.184639
7   107  0.504815  0.585569  0.663745  0.629271
8   108  0.881558  1.000000  0.732801  0.782823
9   109  0.703076  0.944710  0.726910  1.000000
10  110  0.723554  0.207243  0.563288  0.442069
11  111  0.487708  0.951095  0.715079  0.570065
12  112  0.623028  0.592342  0.824465  0.594877
13  113  0.663412  0.466674  0.875925  0.727960
14  114  0.443791  0.765331  0.723306  0.591338
15  115  0.716110  0.639256  0.735073  0.959610
16  116  0.500323  0.375801  0.668860  0.486116
17  117  0.687771  1.000000  0.806959  0.532379
18  118  0.809213  0.512873  0.816200  0.958064
19  119  0.741821  0.801566  0.616313  0.496727
20  120  0.175933  0.806738  0.694725  0.602423
21  121  0.495769  0.563746  0.801094  0.284337
22  122  0.905108  0.191473  0.770905  0.753360
23  123  0.748230  1.000000  0.930641  0.564855
24  124  0.676804  0.900990  0.672971  0.610577
25  125  0.671353  0.360710  0.738466  0.482651
26  126  0.563971  0.522772  0.781380  0.715384
27  127  0.769939  0.854382  0.644284  0.247563
28  128  0.737388  0.693830  0.774838  0.438201
29  129  0.681583  0.274157  0.594459  0.507226
..  ...       ...       ...       ...       ...
70  170  0.878299  0.585930  0.596788  1.000000
71  171  0.532108  0.387636  0.740151  0.373157
72  172  0.329797  0.819853  0.726296  1.000000
73  173  0.657720  0.722923  0.779726  0.069971
74  174  0.572299  0.654394  0.738113  0.496451
75  175  0.832917  0.670670  0.665401  0.923888
76  176  0.624832  0.627990  0.654962  0.595358
77  177  0.897563  0.418599  0.698906  1.000000
78  178  0.682876  0.392876  0.649596  0.429343
79  179  0.615191  0.419064  0.733322  0.866292
80  180  0.700579  0.429901  0.638453  1.000000
81  181  0.583183  0.720789  0.971525  1.000000
82  182  0.518569  1.000000  0.829455  0.813096
83  183  0.547381  0.905886  0.764334  0.598844
84  184  0.778434  0.604180  0.642706  0.521473
85  185  0.726292  0.456794  0.602094  0.355275
86  186  0.508814  0.666065  0.779648  0.656490
87  187  0.443557  0.736631  0.616396  0.624292
88  188  0.509706  0.691898  0.725880  0.727869
89  189  0.514783  0.754498  0.561254  0.898581
90  190  0.250576  1.000000  0.764057  0.845136
91  191  0.745286  0.490003  0.783181  0.597777
92  192  0.694894  0.728217  0.827328  0.647704
93  193  0.916995  0.525267  0.805957  0.548132
94  194  0.764069  0.905535  0.726440  0.856000
95  195  0.768046  0.484223  0.769700  0.981640
96  196  0.588521  0.280656  0.559390  0.619606
97  197  0.447827  0.577835  0.693723  0.462854
98  198  0.682891  0.534703  0.479840  0.661029
99  199  0.642571  1.000000  0.722684  0.437548

[100 rows x 5 columns]

In [ ]:
# Make student ID the 'index'
df = df.set_index('ID')
df

## Selecting Data from Dataframes
There are a number of ways of extracting subsets of the data from a dataframe.
- columns
- iloc: index based, similar to NumPy,
- loc: label based, more similar to a dictionary,
- ix: index and labels (but labels cannot be integers)
### Columns

In [ ]:
# You can extract a column directly from the dataframe.
# Remember that you can collapse the output by clicking in the space to the left.
df[['HW']]
# What happens if you change the double brackets to single brackets?

In [ ]:
# You can also extract multiple columns
df[['ID', 'MT1', 'MT2']]

### Rows

In [ ]:
# iloc selects indices
df.iloc[2:5]

In [ ]:
# loc selects labels
df.loc[[2,3,4]]

You can also select columns and rows at the same time.
<font color='green'>
1. Can you select the Final grade data for students 20-30?<br>
2. How about the MT1 and MT2 data?</font>

In [ ]:
# Try here:

## Creating New Columns
In the last notebook, you created a 'final grade' for the students based on the weighting:
- MT1: 25%
- MT2: 25%
- HW: 20%
- Final: 30%

<font color='green'>
<br>1. Create a new column in the dataframe that computes the final grade.<br>
Hint: the syntax for creating a new column looks very similar to adding a new item to a dictionary!<br>
2. Create a new column that has a 'S' or 'U' based on the .6 cuttoff. Hint: you'll want to use loc for this. First try finding what students have a Final Grade > .6!</font>

If you have trouble with either of these things, search the Pandas documentation. An example for calculating the Midterm Mean is given.

In [ ]:
df['Midterm Mean'] = .5*df['MT1']+.5*df['MT2']

In [ ]:
# Create new columns here:

# Dataframe Utilities
## Computing Statistics
You can also compute statistics on the dataframe as a whole or subsets of the data.

In [ ]:
print('Mean')
print(df.mean())
print('')
print('Max')
print(df.max())
print('')


print('Final')
print(df['Final'].mean())
print('')

print('Homework for Selected Students')
print(df.loc[120:130, 'HW'].mean())

## Plotting
There are also a number of plots from matplotlib that you can create directly from the dataframe.
### Histograms
Try making histograms for different columns. You can also compute the columns mean and standard deviation (.std()) and see if it makes sense given the histogram.

In [ ]:
col = 'Final'
df.plot(y=col, kind='hist')
print(df[col].mean(), df[col].std())

## Finding Correlations in Data
We might hope that the grade on the final exam is a good overall measure of students' knowledge.

One question you could ask is: "what other grades in the course are correlated with the grade on the final?" We can make scatter plots of the different columns versus the final exam to get a qualitative sense (we'll do a quantitative answer later in the course).

In [ ]:
print(df.columns)

In [ ]:
col_comparison = 'HW'
df.plot(x='Final', y=col_comparison, kind='scatter')

<font color='green'>
1. Which other assessments seem to correlate with the final exam grades?<br>
2. Which do not?</font>

Note that this is generated data and not data from a read course.